project:
  type: website
    
website:
  title: "Kara Niewoehner Projects"
  navbar:
    left:
      - text: "Home"
        href: index
      - text: "Gender Inequities through an Economic Lens"
        href: FinalProject
      - text: "Clustering Recruits"
        href: projects/clustering-recruits/ClusteringRecruitsP1
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/kara-niewoehner
      - icon: github
        href: https://github.com/karaniewoehner
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

execute:
  freeze: auto

editor: visual



