project:
  type: website
  render:
    - index.qmd
    - projects/clustering-recruits/ClusteringRecruitsP1.ipynb
    
website:
  title: "Kara Niewoehner Projects"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Gender Inequities through an Economic Lens"
        href: FinalProject.qmd
      - text: "Clustering Recruits"
        href: projects/clustering-recruits/ClusteringRecruitsP1.ipynb
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/kara-niewoehner
      - icon: github
        href: https://github.com/karaniewoehner
format:
  html:
    theme: journal
    css: styles.css
    toc: true

execute:
  freeze: auto

editor: visual



